language: node_js
node_js:
- '9'
dist: trusty
services:
- mongodb
env:
- NODE_ENV=production
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key: 
  app: et-weather-app
  on:
    repo: hohospade/weather-app-1