language: node_js
node_js:
- '9'
dist: trusty
env:
- NODE_ENV=development
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: J1fn69ETsq83lHfFLA6ev02Q10W7xp13GN98+gwoyQRqdbv+Y3r1pg/LO/jBlqqFDFl7/pOUAm9Zhg9Je7Wytrx9lVaHBVET8FgBTjhYrSNcmJhEiMRvz2vugHiHFKLur8O39/yLVDV8O2RyK19ZWl+BLbD85GnEKWVfvIyWBEwnRx8Esl0c28xvFaRddgXislcO2HLYM5rJfIDl8oSSFh9kFRSD9KeGpLJVAS/GvYzpQWS9H3SFhfRCCfm7FHtWFEXgIxk1ibzm24YLYruZXvjddF5pGbQN34/msUj50VKYlZ65y0IdKSjnM6F5uZTbEV8+TagI8SaDILGxXocQTIzbrDasoss/nnyxu5ATl1pQFuXsDMKoyzBvEuvM75o6/lWIzb231Na2mPzjHHN4p6QkSJHi5SxeJSdh4p2QGYs4JVHt0f+/Wk1z3YX2Pmi6AT+rLXNYSJUWqSIbmWajlxGLzBis+boCg71ONoECDIyuoXcjCM0zo/WC5rtMVeEJnPbufRMofoEACDhF0MF2sI4a+u72X+wvRvWf1Q9P68wrYPN30eKlAXwc4aqfA1VHCa11d4+jMbTL5AVYSA5b2MZ8lPvYfO2cxYUo6y827XIwM+i04WrwFcPvwazg0sGWt8f1RbYbVEEuSZjXFdbCLsaXf7OTTx3QPgQ1RaPKzf4=
  app: et-weather-app
  on:
    repo: hohospade/weather-app-1
